<div id="slider">
    <a href="http://www.yahoo.com">
        <img src="<?php echo $this->getSkinUrl('images/shirts.jpg')?>" width="475" height="213">
        <span>First image</span>
    </a>
    <img src="<?php echo $this->getSkinUrl('images/camera.jpg')?>" width="475" height="213">
</div>
<script type="text/javascript">i
jQuery(document).ready(function(){ 
    jQuery('#slider').coinslider({
        width: 475, // width of slider panel
        height: 213, // height of slider panel
        spw: 7, // squares per width
        sph: 5, // squares per height
        delay: 3000, // delay between images in ms
        sDelay: 30, // delay beetwen squares in ms
        opacity: 0.7, // opacity of title and navigation
        titleSpeed: 500, // speed of title appereance in ms
        effect: 'random', // random, swirl, rain, straight
        navigation: true, // prev next and buttons
        links : true, // show images as linksv
        hoverPause: true // pause on hover
    });
});
</script>

